# Generated by Django 5.0.6 on 2024-07-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_pdf_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="pdf_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
